version: "3.3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    depends_on:
      - frontend
      - api
    restart: always
    ports:
      - "80:80"
    networks:
      - bridge-net
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    depends_on:
      - api
    # ports:
    #   - "3000:3000"
    volumes:
      - /app/node_modules
    networks:
      - bridge-net
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /app/node_modules
    # ports:
    #   - "5000:5000"
    networks:
      - bridge-net
networks:
  bridge-net:
    driver: bridge
