name: Build Infrastructure
on:
  push:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: generate test coverage
        working-directory: ./backend
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        id: coverage-check
        uses: vladopajic/go-test-coverage@v2.10.1

        with:
          profile: ./backend/cover.out
          local-prefix: github.com/delta-a-sierra/lux
          threshold-total: 90

      - name: create coverage badge
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 977c23f83f440413bd4a2f6fed55e844
          filename: lux.${{ github.ref_name }}.go-coverage.svg
          label: backend coverage
          message: ${{ steps.coverage-check.outputs.total-coverage }}
          valColorRange: ${{ steps.coverage-check.outputs.total-coverage }}
          maxColorRange: 90
          minColorRange: 50
