name: Build Infrastructure
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "eu-west-2"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_REGION: ${{ secrets.TF_VAR_REGION }}
      TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
      TF_VAR_PROJECT_NAME: ${{ secrets.TF_VAR_PROJECT_NAME }}
      TF_VAR_A_RECORD_NAME: ${{ secrets.TF_VAR_A_RECORD_NAME }}
      TF_VAR_DOMAIN_NAME: ${{ secrets.TF_VAR_DOMAIN_NAME }}
    steps:
      - uses: actions/checkout@v1
      - name: test aws cli conntention
        run: aws sts get-caller-identity
      - uses: hashicorp/setup-terraform@v2
      - name: Initailise infrastructure folder
        run: terraform -chdir=./infrastructure init
      - name: Create terraform plan
        run: terraform -chdir=./infrastructure plan -no-color -input=false
